package asr_data.entity;
// Generated Oct 12, 2018 10:01:36 PM by Hibernate Tools 4.3.1



/**
 * AllData generated by hbm2java
 */
public class AllData  implements java.io.Serializable {


     private int instanceNum;
     private String assetSupportType;
     private Boolean assetCount;
     private String serialNum;
     private String connectionStatus;
     private Integer csi;
     private Integer globalPartyNum;
     private String globalPartyName;
     private String accountName;
     private String topAccount;
     private String accountNum;
     private String accountAlternateName;
     private String highestContractEndDate;
     private String highestContractNumber;
     private String entitlementStatus;
     private String highestContractGracePeriod;
     private String assetStartDate;
     private String assetHlos;
     private String hwAssetDerivedStatus;
     private String hwDescription;
     private String asrActiveFlag;
     private String hwHostname;
     private String asrAssetFirstActivationDat;
     private String asrDeactivationDate;
     private String asrStatus;
     private String asrTechnicalContactEmail;
     private String asrDistributionListEmail;
     private String asrLastHeartBeatRecDate;
     private String asrHostname;
     private String hwAddressLine1;
     private String hwAddressLine2;
     private String hwCity;
     private String hwCounty;
     private String hwState;
     private String hwCountry;
     private String hwCountryArea;
     private String hwGem;
     private Integer hwPostalCode;
     private String hwRegion;
     private String productGlId;
     private String glidGroup;
     private String productType;
     private String pla;
     private String pla2;
     private String productLevel4;
     private String partNum;
     private String productLevel5;
     private String productLevel6;
     private String partyNum;
     private Integer parentInstanceNum;
     private String partyName;
     private String newAssetFlag;
     private String parentSerialNum;
     private String numOfAssets;
     private Boolean activeAssetCount;
     private Boolean nonActiveAssetCount;
     private String idNum;
     private String platinumEnabled;
     private String hasSrInPrevious3Months;
     private Short assetsWithSrInPrevious3;
     private Boolean totalSrsSubmit;
     private Boolean asrSrsSubmit;
     private Short nonAsrSrsSubmit;
     private String willNotConnectFlag;
     private String willNotConnectReason;
     private String willNotConnectComment;
     private String wncNextContactDate;
     private String executive;
     private String entity;
     private String submitDate;
     private String tamEntity;
     private String tamManager;
     private String shortName;
     private String fieldManager;

    public AllData() {
    }

	
    public AllData(int instanceNum) {
        this.instanceNum = instanceNum;
    }
    public AllData(int instanceNum, String assetSupportType, Boolean assetCount, String serialNum, String connectionStatus, Integer csi, Integer globalPartyNum, String globalPartyName, String accountName, String topAccount, String accountNum, String accountAlternateName, String highestContractEndDate, String highestContractNumber, String entitlementStatus, String highestContractGracePeriod, String assetStartDate, String assetHlos, String hwAssetDerivedStatus, String hwDescription, String asrActiveFlag, String hwHostname, String asrAssetFirstActivationDat, String asrDeactivationDate, String asrStatus, String asrTechnicalContactEmail, String asrDistributionListEmail, String asrLastHeartBeatRecDate, String asrHostname, String hwAddressLine1, String hwAddressLine2, String hwCity, String hwCounty, String hwState, String hwCountry, String hwCountryArea, String hwGem, Integer hwPostalCode, String hwRegion, String productGlId, String glidGroup, String productType, String pla, String pla2, String productLevel4, String partNum, String productLevel5, String productLevel6, String partyNum, Integer parentInstanceNum, String partyName, String newAssetFlag, String parentSerialNum, String numOfAssets, Boolean activeAssetCount, Boolean nonActiveAssetCount, String idNum, String platinumEnabled, String hasSrInPrevious3Months, Short assetsWithSrInPrevious3, Boolean totalSrsSubmit, Boolean asrSrsSubmit, Short nonAsrSrsSubmit, String willNotConnectFlag, String willNotConnectReason, String willNotConnectComment, String wncNextContactDate, String executive, String entity, String submitDate, String tamEntity, String tamManager, String shortName, String fieldManager) {
       this.instanceNum = instanceNum;
       this.assetSupportType = assetSupportType;
       this.assetCount = assetCount;
       this.serialNum = serialNum;
       this.connectionStatus = connectionStatus;
       this.csi = csi;
       this.globalPartyNum = globalPartyNum;
       this.globalPartyName = globalPartyName;
       this.accountName = accountName;
       this.topAccount = topAccount;
       this.accountNum = accountNum;
       this.accountAlternateName = accountAlternateName;
       this.highestContractEndDate = highestContractEndDate;
       this.highestContractNumber = highestContractNumber;
       this.entitlementStatus = entitlementStatus;
       this.highestContractGracePeriod = highestContractGracePeriod;
       this.assetStartDate = assetStartDate;
       this.assetHlos = assetHlos;
       this.hwAssetDerivedStatus = hwAssetDerivedStatus;
       this.hwDescription = hwDescription;
       this.asrActiveFlag = asrActiveFlag;
       this.hwHostname = hwHostname;
       this.asrAssetFirstActivationDat = asrAssetFirstActivationDat;
       this.asrDeactivationDate = asrDeactivationDate;
       this.asrStatus = asrStatus;
       this.asrTechnicalContactEmail = asrTechnicalContactEmail;
       this.asrDistributionListEmail = asrDistributionListEmail;
       this.asrLastHeartBeatRecDate = asrLastHeartBeatRecDate;
       this.asrHostname = asrHostname;
       this.hwAddressLine1 = hwAddressLine1;
       this.hwAddressLine2 = hwAddressLine2;
       this.hwCity = hwCity;
       this.hwCounty = hwCounty;
       this.hwState = hwState;
       this.hwCountry = hwCountry;
       this.hwCountryArea = hwCountryArea;
       this.hwGem = hwGem;
       this.hwPostalCode = hwPostalCode;
       this.hwRegion = hwRegion;
       this.productGlId = productGlId;
       this.glidGroup = glidGroup;
       this.productType = productType;
       this.pla = pla;
       this.pla2 = pla2;
       this.productLevel4 = productLevel4;
       this.partNum = partNum;
       this.productLevel5 = productLevel5;
       this.productLevel6 = productLevel6;
       this.partyNum = partyNum;
       this.parentInstanceNum = parentInstanceNum;
       this.partyName = partyName;
       this.newAssetFlag = newAssetFlag;
       this.parentSerialNum = parentSerialNum;
       this.numOfAssets = numOfAssets;
       this.activeAssetCount = activeAssetCount;
       this.nonActiveAssetCount = nonActiveAssetCount;
       this.idNum = idNum;
       this.platinumEnabled = platinumEnabled;
       this.hasSrInPrevious3Months = hasSrInPrevious3Months;
       this.assetsWithSrInPrevious3 = assetsWithSrInPrevious3;
       this.totalSrsSubmit = totalSrsSubmit;
       this.asrSrsSubmit = asrSrsSubmit;
       this.nonAsrSrsSubmit = nonAsrSrsSubmit;
       this.willNotConnectFlag = willNotConnectFlag;
       this.willNotConnectReason = willNotConnectReason;
       this.willNotConnectComment = willNotConnectComment;
       this.wncNextContactDate = wncNextContactDate;
       this.executive = executive;
       this.entity = entity;
       this.submitDate = submitDate;
       this.tamEntity = tamEntity;
       this.tamManager = tamManager;
       this.shortName = shortName;
       this.fieldManager = fieldManager;
    }
   
    public int getInstanceNum() {
        return this.instanceNum;
    }
    
    public void setInstanceNum(int instanceNum) {
        this.instanceNum = instanceNum;
    }
    public String getAssetSupportType() {
        return this.assetSupportType;
    }
    
    public void setAssetSupportType(String assetSupportType) {
        this.assetSupportType = assetSupportType;
    }
    public Boolean getAssetCount() {
        return this.assetCount;
    }
    
    public void setAssetCount(Boolean assetCount) {
        this.assetCount = assetCount;
    }
    public String getSerialNum() {
        return this.serialNum;
    }
    
    public void setSerialNum(String serialNum) {
        this.serialNum = serialNum;
    }
    public String getConnectionStatus() {
        return this.connectionStatus;
    }
    
    public void setConnectionStatus(String connectionStatus) {
        this.connectionStatus = connectionStatus;
    }
    public Integer getCsi() {
        return this.csi;
    }
    
    public void setCsi(Integer csi) {
        this.csi = csi;
    }
    public Integer getGlobalPartyNum() {
        return this.globalPartyNum;
    }
    
    public void setGlobalPartyNum(Integer globalPartyNum) {
        this.globalPartyNum = globalPartyNum;
    }
    public String getGlobalPartyName() {
        return this.globalPartyName;
    }
    
    public void setGlobalPartyName(String globalPartyName) {
        this.globalPartyName = globalPartyName;
    }
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    public String getTopAccount() {
        return this.topAccount;
    }
    
    public void setTopAccount(String topAccount) {
        this.topAccount = topAccount;
    }
    public String getAccountNum() {
        return this.accountNum;
    }
    
    public void setAccountNum(String accountNum) {
        this.accountNum = accountNum;
    }
    public String getAccountAlternateName() {
        return this.accountAlternateName;
    }
    
    public void setAccountAlternateName(String accountAlternateName) {
        this.accountAlternateName = accountAlternateName;
    }
    public String getHighestContractEndDate() {
        return this.highestContractEndDate;
    }
    
    public void setHighestContractEndDate(String highestContractEndDate) {
        this.highestContractEndDate = highestContractEndDate;
    }
    public String getHighestContractNumber() {
        return this.highestContractNumber;
    }
    
    public void setHighestContractNumber(String highestContractNumber) {
        this.highestContractNumber = highestContractNumber;
    }
    public String getEntitlementStatus() {
        return this.entitlementStatus;
    }
    
    public void setEntitlementStatus(String entitlementStatus) {
        this.entitlementStatus = entitlementStatus;
    }
    public String getHighestContractGracePeriod() {
        return this.highestContractGracePeriod;
    }
    
    public void setHighestContractGracePeriod(String highestContractGracePeriod) {
        this.highestContractGracePeriod = highestContractGracePeriod;
    }
    public String getAssetStartDate() {
        return this.assetStartDate;
    }
    
    public void setAssetStartDate(String assetStartDate) {
        this.assetStartDate = assetStartDate;
    }
    public String getAssetHlos() {
        return this.assetHlos;
    }
    
    public void setAssetHlos(String assetHlos) {
        this.assetHlos = assetHlos;
    }
    public String getHwAssetDerivedStatus() {
        return this.hwAssetDerivedStatus;
    }
    
    public void setHwAssetDerivedStatus(String hwAssetDerivedStatus) {
        this.hwAssetDerivedStatus = hwAssetDerivedStatus;
    }
    public String getHwDescription() {
        return this.hwDescription;
    }
    
    public void setHwDescription(String hwDescription) {
        this.hwDescription = hwDescription;
    }
    public String getAsrActiveFlag() {
        return this.asrActiveFlag;
    }
    
    public void setAsrActiveFlag(String asrActiveFlag) {
        this.asrActiveFlag = asrActiveFlag;
    }
    public String getHwHostname() {
        return this.hwHostname;
    }
    
    public void setHwHostname(String hwHostname) {
        this.hwHostname = hwHostname;
    }
    public String getAsrAssetFirstActivationDat() {
        return this.asrAssetFirstActivationDat;
    }
    
    public void setAsrAssetFirstActivationDat(String asrAssetFirstActivationDat) {
        this.asrAssetFirstActivationDat = asrAssetFirstActivationDat;
    }
    public String getAsrDeactivationDate() {
        return this.asrDeactivationDate;
    }
    
    public void setAsrDeactivationDate(String asrDeactivationDate) {
        this.asrDeactivationDate = asrDeactivationDate;
    }
    public String getAsrStatus() {
        return this.asrStatus;
    }
    
    public void setAsrStatus(String asrStatus) {
        this.asrStatus = asrStatus;
    }
    public String getAsrTechnicalContactEmail() {
        return this.asrTechnicalContactEmail;
    }
    
    public void setAsrTechnicalContactEmail(String asrTechnicalContactEmail) {
        this.asrTechnicalContactEmail = asrTechnicalContactEmail;
    }
    public String getAsrDistributionListEmail() {
        return this.asrDistributionListEmail;
    }
    
    public void setAsrDistributionListEmail(String asrDistributionListEmail) {
        this.asrDistributionListEmail = asrDistributionListEmail;
    }
    public String getAsrLastHeartBeatRecDate() {
        return this.asrLastHeartBeatRecDate;
    }
    
    public void setAsrLastHeartBeatRecDate(String asrLastHeartBeatRecDate) {
        this.asrLastHeartBeatRecDate = asrLastHeartBeatRecDate;
    }
    public String getAsrHostname() {
        return this.asrHostname;
    }
    
    public void setAsrHostname(String asrHostname) {
        this.asrHostname = asrHostname;
    }
    public String getHwAddressLine1() {
        return this.hwAddressLine1;
    }
    
    public void setHwAddressLine1(String hwAddressLine1) {
        this.hwAddressLine1 = hwAddressLine1;
    }
    public String getHwAddressLine2() {
        return this.hwAddressLine2;
    }
    
    public void setHwAddressLine2(String hwAddressLine2) {
        this.hwAddressLine2 = hwAddressLine2;
    }
    public String getHwCity() {
        return this.hwCity;
    }
    
    public void setHwCity(String hwCity) {
        this.hwCity = hwCity;
    }
    public String getHwCounty() {
        return this.hwCounty;
    }
    
    public void setHwCounty(String hwCounty) {
        this.hwCounty = hwCounty;
    }
    public String getHwState() {
        return this.hwState;
    }
    
    public void setHwState(String hwState) {
        this.hwState = hwState;
    }
    public String getHwCountry() {
        return this.hwCountry;
    }
    
    public void setHwCountry(String hwCountry) {
        this.hwCountry = hwCountry;
    }
    public String getHwCountryArea() {
        return this.hwCountryArea;
    }
    
    public void setHwCountryArea(String hwCountryArea) {
        this.hwCountryArea = hwCountryArea;
    }
    public String getHwGem() {
        return this.hwGem;
    }
    
    public void setHwGem(String hwGem) {
        this.hwGem = hwGem;
    }
    public Integer getHwPostalCode() {
        return this.hwPostalCode;
    }
    
    public void setHwPostalCode(Integer hwPostalCode) {
        this.hwPostalCode = hwPostalCode;
    }
    public String getHwRegion() {
        return this.hwRegion;
    }
    
    public void setHwRegion(String hwRegion) {
        this.hwRegion = hwRegion;
    }
    public String getProductGlId() {
        return this.productGlId;
    }
    
    public void setProductGlId(String productGlId) {
        this.productGlId = productGlId;
    }
    public String getGlidGroup() {
        return this.glidGroup;
    }
    
    public void setGlidGroup(String glidGroup) {
        this.glidGroup = glidGroup;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public String getPla() {
        return this.pla;
    }
    
    public void setPla(String pla) {
        this.pla = pla;
    }
    public String getPla2() {
        return this.pla2;
    }
    
    public void setPla2(String pla2) {
        this.pla2 = pla2;
    }
    public String getProductLevel4() {
        return this.productLevel4;
    }
    
    public void setProductLevel4(String productLevel4) {
        this.productLevel4 = productLevel4;
    }
    public String getPartNum() {
        return this.partNum;
    }
    
    public void setPartNum(String partNum) {
        this.partNum = partNum;
    }
    public String getProductLevel5() {
        return this.productLevel5;
    }
    
    public void setProductLevel5(String productLevel5) {
        this.productLevel5 = productLevel5;
    }
    public String getProductLevel6() {
        return this.productLevel6;
    }
    
    public void setProductLevel6(String productLevel6) {
        this.productLevel6 = productLevel6;
    }
    public String getPartyNum() {
        return this.partyNum;
    }
    
    public void setPartyNum(String partyNum) {
        this.partyNum = partyNum;
    }
    public Integer getParentInstanceNum() {
        return this.parentInstanceNum;
    }
    
    public void setParentInstanceNum(Integer parentInstanceNum) {
        this.parentInstanceNum = parentInstanceNum;
    }
    public String getPartyName() {
        return this.partyName;
    }
    
    public void setPartyName(String partyName) {
        this.partyName = partyName;
    }
    public String getNewAssetFlag() {
        return this.newAssetFlag;
    }
    
    public void setNewAssetFlag(String newAssetFlag) {
        this.newAssetFlag = newAssetFlag;
    }
    public String getParentSerialNum() {
        return this.parentSerialNum;
    }
    
    public void setParentSerialNum(String parentSerialNum) {
        this.parentSerialNum = parentSerialNum;
    }
    public String getNumOfAssets() {
        return this.numOfAssets;
    }
    
    public void setNumOfAssets(String numOfAssets) {
        this.numOfAssets = numOfAssets;
    }
    public Boolean getActiveAssetCount() {
        return this.activeAssetCount;
    }
    
    public void setActiveAssetCount(Boolean activeAssetCount) {
        this.activeAssetCount = activeAssetCount;
    }
    public Boolean getNonActiveAssetCount() {
        return this.nonActiveAssetCount;
    }
    
    public void setNonActiveAssetCount(Boolean nonActiveAssetCount) {
        this.nonActiveAssetCount = nonActiveAssetCount;
    }
    public String getIdNum() {
        return this.idNum;
    }
    
    public void setIdNum(String idNum) {
        this.idNum = idNum;
    }
    public String getPlatinumEnabled() {
        return this.platinumEnabled;
    }
    
    public void setPlatinumEnabled(String platinumEnabled) {
        this.platinumEnabled = platinumEnabled;
    }
    public String getHasSrInPrevious3Months() {
        return this.hasSrInPrevious3Months;
    }
    
    public void setHasSrInPrevious3Months(String hasSrInPrevious3Months) {
        this.hasSrInPrevious3Months = hasSrInPrevious3Months;
    }
    public Short getAssetsWithSrInPrevious3() {
        return this.assetsWithSrInPrevious3;
    }
    
    public void setAssetsWithSrInPrevious3(Short assetsWithSrInPrevious3) {
        this.assetsWithSrInPrevious3 = assetsWithSrInPrevious3;
    }
    public Boolean getTotalSrsSubmit() {
        return this.totalSrsSubmit;
    }
    
    public void setTotalSrsSubmit(Boolean totalSrsSubmit) {
        this.totalSrsSubmit = totalSrsSubmit;
    }
    public Boolean getAsrSrsSubmit() {
        return this.asrSrsSubmit;
    }
    
    public void setAsrSrsSubmit(Boolean asrSrsSubmit) {
        this.asrSrsSubmit = asrSrsSubmit;
    }
    public Short getNonAsrSrsSubmit() {
        return this.nonAsrSrsSubmit;
    }
    
    public void setNonAsrSrsSubmit(Short nonAsrSrsSubmit) {
        this.nonAsrSrsSubmit = nonAsrSrsSubmit;
    }
    public String getWillNotConnectFlag() {
        return this.willNotConnectFlag;
    }
    
    public void setWillNotConnectFlag(String willNotConnectFlag) {
        this.willNotConnectFlag = willNotConnectFlag;
    }
    public String getWillNotConnectReason() {
        return this.willNotConnectReason;
    }
    
    public void setWillNotConnectReason(String willNotConnectReason) {
        this.willNotConnectReason = willNotConnectReason;
    }
    public String getWillNotConnectComment() {
        return this.willNotConnectComment;
    }
    
    public void setWillNotConnectComment(String willNotConnectComment) {
        this.willNotConnectComment = willNotConnectComment;
    }
    public String getWncNextContactDate() {
        return this.wncNextContactDate;
    }
    
    public void setWncNextContactDate(String wncNextContactDate) {
        this.wncNextContactDate = wncNextContactDate;
    }
    public String getExecutive() {
        return this.executive;
    }
    
    public void setExecutive(String executive) {
        this.executive = executive;
    }
    public String getEntity() {
        return this.entity;
    }
    
    public void setEntity(String entity) {
        this.entity = entity;
    }
    public String getSubmitDate() {
        return this.submitDate;
    }
    
    public void setSubmitDate(String submitDate) {
        this.submitDate = submitDate;
    }
    public String getTamEntity() {
        return this.tamEntity;
    }
    
    public void setTamEntity(String tamEntity) {
        this.tamEntity = tamEntity;
    }
    public String getTamManager() {
        return this.tamManager;
    }
    
    public void setTamManager(String tamManager) {
        this.tamManager = tamManager;
    }
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    public String getFieldManager() {
        return this.fieldManager;
    }
    
    public void setFieldManager(String fieldManager) {
        this.fieldManager = fieldManager;
    }




}


